### ISSUE TITLE
Manygauss returns NaN

### ISSUE THREAD

**Issue by LydiaMak** [legolason/PyQSOFit#16]
Hi,

First thanks a lot for the very well-written and easy-to-use code!

I have a problem while trying to fit a starforming galaxy (spec-1172-52759-0097). Although I've managed to fit kinda well the spectrum lines using for qsopar:

newdata = np.rec.array([(6564.61,'Ha',6400.,6800.,'Ha_br',3,5e-3,0.004,0.05,0.015,0,0,0,0.05),\
                        (6564.61,'Ha',6400.,6800.,'Ha_na',1,1e-3,2e-4,0.0017,0.01,1,1,0,0.02),\
                        (6549.85,'Ha',6400.,6800.,'NII6549',1,1e-3,2.3e-4,0.0017,5e-3,1,1,1,0.001),\
                        (6585.28,'Ha',6400.,6800.,'NII6585',1,1e-3,2.3e-4,0.0017,5e-3,1,1,1,0.003),\
                        (6718.29,'Ha',6400.,6800.,'SII6718',1,1e-3,2.3e-4,0.0017,5e-3,1,1,2,0.001),\
                        (6732.67,'Ha',6400.,6800.,'SII6732',1,1e-3,2.3e-4,0.0017,5e-3,1,1,2,0.001),\
                        (4862.68,'Hb',4640.,5100.,'Hb_br',1,5e-3,0.004,0.05,0.01,0,0,0,0.01),\
                        (4862.68,'Hb',4640.,5100.,'Hb_na',1,0.5e-3,2.3e-4,0.0017,0.01,1,1,0,0.002),\
                        (4960.30,'Hb',4640.,5100.,'OIII4959c',1,1e-3,2.3e-4,0.0017,0.01,1,1,0,0.002),\
                        (5008.24,'Hb',4640.,5100.,'OIII5007c',1,1e-3,2.3e-4,0.0017,0.01,1,1,0,0.004),\
                        (4960.30,'Hb',4640.,5100.,'OIII4959w',1,3e-3,2.3e-4,0.004,0.01,2,2,0,0.001),\
                        (5008.24,'Hb',4640.,5100.,'OIII5007w',1,3e-3,2.3e-4,0.004,0.01,2,2,0,0.002),\
                        #(4687.02,'Hb',4640.,5100.,'HeII4687_br',1,5e-3,0.004,0.05,0.005,0,0,0,0.001),\
                        #(4687.02,'Hb',4640.,5100.,'HeII4687_na',1,1e-3,2.3e-4,0.0017,0.005,1,1,0,0.001),\
                        #(3934.78,'CaII',3900.,3960.,'CaII3934',2,1e-3,3.333e-4,0.0017,0.01,99,0,0,-0.001),\
                        #(3728.48,'OII',3650.,3800.,'OII3728',1,1e-3,3.333e-4,0.0017,0.01,1,1,0,0.001),\
                        #(3426.84,'NeV',3380.,3480.,'NeV3426',1,1e-3,3.333e-4,0.0017,0.01,0,0,0,0.001),\
                        #(3426.84,'NeV',3380.,3480.,'NeV3426_br',1,5e-3,0.0025,0.02,0.01,0,0,0,0.001),\
                        ],\

When I try to plot the different parts using the example:

fig=plt.figure(figsize=(15,8))
#plot the quasar rest frame spectrum after removed the host galaxy component
plt.plot(q.wave,q.flux,'grey')              
plt.plot(q.wave,q.err,'r')

#To plot the whole model, we use Manygauss to reappear the line fitting results saved in gauss_result  
plt.plot(q.wave,q.Manygauss(np.log(q.wave),q.gauss_result)+q.f_conti_model,'b',label='line',lw=2)
plt.plot(q.wave,q.f_conti_model,'c',lw=2)
plt.plot(q.wave,q.PL_poly,'orange',lw=2)
plt.plot(q.wave,q.host,'m',lw=2)

plt.xlim(3500,8000)
plt.xlabel(r'$\rm Rest \, Wavelength$ ($\rm \AA$)',fontsize = 20)
plt.ylabel(r'$\rm f_{\lambda}$ ($\rm 10^{-17} erg\;s^{-1}\;cm^{-2}\;\AA^{-1}$)',fontsize = 20)

I see that Manygauss (Onegauss as well) gives Nan. If you have any idea why this happens or you see any mistake in my code, please let me know!

Thanks,
Lydia

**Comment by legolason** [comment]
Hi Lydia, 

Manygauss and Onegauss are designed to fit the broad emission line. Since your star-forming galaxy does not have any broad emission lines (PCA gives zero AGN fraction), thus it just gives zeros. You got Nan, I guess it is because you are using an order version.  My code just fits the galaxy with PCA, if you want to get galaxy information try pPXF  https://www-astro.physics.ox.ac.uk/~mxc/software/

Good luck,
Hengxiao

**Comment by legolason** [comment]
It uses the PCA method, so the star-forming fitting is a result of a combination of different galaxy templates, if you want to reproduce it, you just need to plot q.host if I remember correctly.

**Comment by LydiaMak** [comment]
Great thanks!
