### ISSUE TITLE
Approximate FWHM of the line

### ISSUE THREAD

**Issue by LydiaMak** [legolason/PyQSOFit#19]
Hi,

Is there a way to calculate the "total" approximate FWHM for a line with multiple components using the code itself?

Is that the e.g. Hb_whole_br_fwhm in q.all_result?

Thanks,

Lydia

**Comment by legolason** [comment]
Yes, Hb_whole_br_fwhm is the thing you are looking for, it combines all components and measures the line width.

**Comment by LydiaMak** [comment]
Thanks a lot!
