### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by astro-fermi** [legolason/PyQSOFit#2]
Hello,

First of all, many thanks for such a nice package, especially for beginners. I was trying to use to fit a SDSS spectrum of a quasar (spec-4751-55646-0776.fits, z=0.966). My input is as follows:
q.Fit(name = None,nsmooth = 1, and_or_mask = False, deredden = True, reject_badpix = False, wave_range = None,\
      wave_mask =None, decomposition_host = False, Mi = None, npca_gal = 5, npca_qso = 20, \
      Fe_uv_op = True, poly = True, BC = False, rej_abs = False, initial_guess = None, MC = False, \
      n_trails = 5, linefit = True, tie_lambda = True, tie_width = True, tie_flux_1 = True, tie_flux_2 = True,\
      save_result = True, plot_fig = True,save_fig = True, plot_line_name = True, plot_legend = True, \
      dustmap_path = path4, save_fig_path = path3, save_fits_path = path2,save_fits_name = 'result')

If I keep 'decomposition_host = False,' I get the following 
<img width="1468" alt="host_false" src="https://user-images.githubusercontent.com/5036959/52438875-97f3eb80-2b1a-11e9-8075-23bfe3dc6e45.png">
and output H_beta parameters are as follows:
Hb complex:
FWHM (km/s) 57152.16835323342
Sigma (km/s) 24000.2651644381
EW (A) inf
Peak (A) 1905.9108674658348
area (10^(-17) erg/s/cm^2) 4729.824740365793

On the other hand, when I keep decomposition_host = True, the results changes drastically. The output plot is as follows:
<img width="1430" alt="host_true" src="https://user-images.githubusercontent.com/5036959/52438962-ca054d80-2b1a-11e9-9beb-d7c4f1eb04c6.png">
Hb complex:
FWHM (km/s) 2944.4194923130817
Sigma (km/s) 1234.1006932715818
EW (A) 16.185124898153276
Peak (A) 4859.899850785794
area (10^(-17) erg/s/cm^2) 399.0622589819461

So, it appears that by including host decomposition, it doesn't fit the bluer part (no Mg II or C III) but H_beta line parameters are OK. If I ignore host decomposition, the code fits throughout but the H_beta fitting parameters are weird. Let me know what do you suggest.

If you could update the documentation regarding how to print the errors in the parameters derived from the MC, it would be great.

Also, instead of SDSS spectrum, can I supply the input as a text file with three columns: lambda, flux, and flux_error? Do I need to modify the source code for this purpose?

Thank you in advance.

**Comment by legolason** [comment]
So, it appears that by including host decomposition, it doesn't fit the bluer part (no Mg II or C III) but H_beta line parameters are OK. If I ignore host decomposition, the code fits throughout but the H_beta fitting parameters are weird. Let me know what do you suggest.
Yes, this is caused by the limited host templet (starts from 3500A), so the code will cut the blue part of the spectrum since high redshift sources are not supposed to fit with a host. For the first example, they are not the parameters of Hb! they are CIII, see the peak it's 1905A. Try to understand what you print, you need to change the q.linelist, q.gauss_result. 
  

If you could update the documentation regarding how to print the errors in the parameters derived from the MC, it would be great.
It's very easy, you can just set MC = 50, and save the results to fits. Then you can get the errors for all parameters. 

Also, instead of SDSS spectrum, can I supply the input as a text file with three columns: lambda, flux, and flux_error? Do I need to modify the source code for this purpose?
you'd better transfer the wavelength to delta loglam = 1.e-4 as SDSS spectrum, so that the parameters come from line_prop will be right.

**Comment by astro-fermi** [comment]
Many thanks for your prompt reply. This may be a naive question but how do
I transfer the wavelength to maintain the log lambda same as in SDSS? Say,
I have w1, w2, w3, w4 .... wavelengths for f1, f2, f3, f4 .... fluxes.
Should I try some interpolation?

Many thanks again.

**Comment by legolason** [comment]
This may be a naive question but how do I transfer the wavelength to maintain the log lambda same as in SDSS? Say, I have w1, w2, w3, w4 .... wavelengths for f1, f2, f3, f4 .... fluxes. Should I try some interpolation?
Yes, interpolation is right. just make sure the interval is 1.e-4 in log scale.

 Also, I just noticed that I am running the same command fwhm,sigma,ew,peak,area = q.line_prop(q.linelist[6][0],q.gauss_result[0:27]) both the time. When host decomposition is True, it prints results associated with H_beta line. However, when host decomposition is set to False, the same command is printing the results for C III line, as you pointed out.

q.gauss_result saves all the Gaussian components you have used. For each line has three parameters, the second (3n+1, n=0,1,2...) is the central wavelength of this Gaussian. You just need to figure out, say these three parameters are for which Gaussian. See the details in the doc.

**Comment by astro-fermi** [comment]
Hello,

I have one small question regarding the result.fits file where all the output parameters are saved. Please tell me the units of line 'FWHM', 'line area', and 'L5100' columns. I tried to look in the documentation, however, couldn't find it.

Thank you.

**Comment by legolason** [comment]
Thanks for pointing this, I will add these info. 
FWHM   km/s
Line area  erg/s/cm^2
L5100  erg/s

**Comment by astro-fermi** [comment]
Hi,
I was reading a few recent papers and found that in some AGNs, especially narrow line Seyfert 1 galaxies, emission line profiles are better described by a Lorentzian rather than Gaussian profile.  Therefore, may I request you to kindly explore the possibility to fit the emission lines with a Lorentzian. This may be needed only for broad components and an option can be  provided to a user if he/she opts to use Gaussian or Lorentzian profiles. Though my programming knowledge is limited, I will be happy to do the testing and report the bugs.

Also, since narrow line Seyfert 1 galaxies are known to exhibit strong Fe complexes, how can I extract FeII flux ((4434-4684 angstrom)? This information may help in calculating strength of Fe II complexes by taking the ratio of FeII flux to H_beta broad line flux.

One trivial doubt: is the line area same as the line flux?

Thank you.

**Comment by legolason** [comment]
> Hi,
> I was reading a few recent papers and found that in some AGNs, especially narrow line Seyfert 1 galaxies, emission line profiles are better described by a Lorentzian rather than Gaussian profile. Therefore, may I request you to kindly explore the possibility to fit the emission lines with a Lorentzian. This may be needed only for broad components and an option can be provided to a user if he/she opts to use Gaussian or Lorentzian profiles. Though my programming knowledge is limited, I will be happy to do the testing and report the bugs.
> 
> Also, since narrow line Seyfert 1 galaxies are known to exhibit strong Fe complexes, how can I extract FeII flux ((4434-4684 angstrom)? This information may help in calculating strength of Fe II complexes by taking the ratio of FeII flux to H_beta broad line flux.
> 
> One trivial doubt: is the line area same as the line flux?
> 
> Thank you.

Hi, 
Your suggestion is helpful. I know some other profiles are better than Gaussian to describe the line profiles. It is a little complex if we want to transfer all the Gaussian to Lorentzian since we need to adjust a lot of limits of line width. I would explore this maybe in the next version since someone also hopes I can use Gaussian-Hermitian instead. But sorry I don't have the time now... 

For 4434-4684 angstrom Fe II. You can get the parameters of optical Fe from q.conti_result & q.conti_result_name. It saves all the information about the continuum. You can reproduce the Fe component and get what you want. 

Yes, the line area is the line flux 

Thanks！

**Comment by astro-fermi** [comment]
Hi,

Thanks for the reply. I printed q.conti_result_name and got the following output

['ra' 'dec' 'plateid' 'MJD' 'fiberid' 'redshift' 'SN_ratio_conti'
 'Fe_uv_FWHM' 'Fe_uv_FWHM_err' 'Fe_op_FWHM' 'Fe_op_FWHM_err' 'PL_norm'
 'PL_norm_err' 'PL_slope' 'PL_slope_err' 'POLY_a' 'POLY_a_err' 'POLY_b'
 'POLY_b_err' 'POLY_c' 'POLY_c_err' 'L1350' 'L1350_err' 'L3000'
 'L3000_err' 'L5100' 'L5100_err']

Since I was unsure about how to get Fe flux (4434-4684 A) from this, I looked into the source code and found a parameter 'q.f_fe_op_model' which is an array. But, now I am unable to get the desired flux from this. Please help me with this.

Also, to determine the classification of an AGN as a narrow line Seyfert 1, one needs the ratio of the [O III] to Hbeta fluxes. I can get the broad Hbeta line flux from the fit. But, how to get the flux of the [O III] component and also narrow Hbeta line? This is because the ratio is between the total [O III] to total Hbeta line fluxes. It would be great if you could add this feature so that in the output result.fits file, parameters associated with both broad and narrow line components for all the fitted lines can be saved.

I apologize for persisting with questions. Actually, I lack the necessary expertise and trying hard to learn it. Nevertheless, the PyQSOfit is really a great help for a beginner like me.

Thanks for all the help.

**Comment by legolason** [comment]
you can use plt.plot(q.wave,q.f_conti_model-q.PL_poly_BC) to plot the observed Iron template, then you can sum up what range you want. Here q.f_conti_model includes PL+POLY+BC+Fe while q.PL_poly_BC do not have Fe. 

read this page for the narrow line flux. 
https://github.com/legolason/PyQSOfit_narrowline_example/blob/master/example_yasir.ipynb

**Comment by astro-fermi** [comment]
Hi @legolason 
Thanks. How to compute the S/N of emission lines (Hbeta, MgII and CIV)? I read your recent paper (arXiv:1908.00072) and noted that this quantity was used to perform the source selection.
Thank you.

**Comment by legolason** [comment]
Yes, if it including the error, you can use q.line_result[30:36:2] to pick out the Gaussian parameters, or you can change the list to an array.

to calculate the SN you can choose a line range e.g., mgii [2750,2850] and a background range [3000,3100]
use the average line flux/ std of the background flux.

**Comment by astro-fermi** [comment]
Hi,
I just forgot to ask that how to compute uncertainties in the narrow line parameters. q.line_prop command gives the FWHM and other parameters as output but not errors.

**Comment by legolason** [comment]
like run MCMC, you need to fit the same object e.g., 50 times and you will get 50 FWHM of the narrow line, then cut the 16 to 84% as the error range

**Comment by SaikhomJohnson** [comment]
how to print error in fwhm, error in sigma, error in ew, error in peak and error in area using pyqsofit
