### ISSUE TITLE
Continuum fitting

### ISSUE THREAD

**Issue by LydiaMak** [legolason/PyQSOFit#23]
I have an issue with continuum fitting and I wonder if you have come across this or can suggest a solution. When I fit the continuum for the full spectrum with simply the power-law it doesn't fit very well on the red part. When I add a polynomial contribution it behaves weird. See attached files. Playing around with the initial guess doesn't change things. Let me know if you have any suggestion. Fitting the blue and the red spectrum separately can be a solution but I would like it if it was possible to fit the whole spectrum.
![Screenshot 2021-11-04 at 11 25 17](https://user-images.githubusercontent.com/23122380/140290369-c2b47c08-3b9b-4348-b54a-03059c2b1c43.png)
![Screenshot 2021-11-04 at 11 31 15](https://user-images.githubusercontent.com/23122380/140290375-0a603cb8-bb6c-4046-b42d-ad075c41f53b.png)

**Comment by legolason** [comment]
check the continuum fitting windows, make sure your continuum is constrained in a fitting window.  Like in your first case, make sure there is a window around 7000-7500

**Comment by LydiaMak** [comment]
Hi, thanks for the reply. Actually there are I think enough windows for >7000.
![Screenshot 2021-11-07 at 09 53 48](https://user-images.githubusercontent.com/23122380/140637170-27182a86-98eb-41b6-bef5-d9082b831be7.png)

**Comment by LydiaMak** [comment]
I figured out that a better solution for now is to remove the windows <5000.

**Comment by LydiaMak** [comment]
Actually this causes problems with the blue part so I reopen the issue.

**Comment by legolason** [comment]
your figure looks very weird, it seems there is a very low data point > 8500A and drags the continuum to a very level?

**Comment by LydiaMak** [comment]
I changed the windows a bit and it gave me better results. Thanks!
