### ISSUE TITLE
Min/max sigma

### ISSUE THREAD

**Issue by LydiaMak** [legolason/PyQSOFit#24]
Hi again,

I am kinda confused with the way the limits are set. E.g. if the limits in FWHM 2000-10000 km/s what's the correct numbers for qsopar? I am afraid that either I am doing something wrong (in trying to go from FWHM to sigma) or I have misunderstood something as my numbers are quite different.

Thanks,

Lydia

**Comment by legolason** [comment]
You can use the CALFWHM to calculate the line width,  like  q.CALFWHM(wave,0.0017) ~ 1200 km/s

**Comment by LydiaMak** [comment]
Thanks for this! It's very helpful! I have another question. My understanding is that tie_width is tying these with the same windex (third from end). However I have done it for three lines but the FWHM in the end is quite different for each line. Am I getting something wrong?
