### ISSUE TITLE
Question about tie_width.

### ISSUE THREAD

**Issue by LydiaMak** [legolason/PyQSOFit#25]
My understanding is that tie_width is tying these with the same windex (third from end). However I have done it for three lines but the FWHM in the end is quite different for each line. Am I getting something wrong?

Thanks,

Lydia

**Comment by legolason** [comment]
For the current version, we are able to tie two groups of lines, e.g., windex = 1 and 2. I'm not sure how you did this.

**Comment by LydiaMak** [comment]
To explain a bit more.I want to tie the HeII and NIII to Hbeta broad in terms of lambda and width. I tried this: 

(4862.68,'Hb',4640.,5100.,'Hb_br',1,3e-3,0.0017,0.015,0.0022,0,0,0,0.05),\
 (4862.68,'Hb',4640.,5100.,'Hb_na',1,1e-3,7e-4,0.0017,0.0022,1,1,0,0.002),\
............................                        
(4640.64,'Hb',4600.,4660.,'NIII4640',1,3e-3,0.0017,0.015,0.0022,0,0,1,0.001),\
(4687.02,'Hb',4640.,5100.,'HeII4687',1,3e-3,0.0017,0.015,0.0022,0,0,1,0.003),\
....

but I get very different FWHM for Hbeta and HeII. Let me know what you think.

**Comment by legolason** [comment]
Oh,  I see, the problem here is that the code is designed to tie two lines at a time, if you really want to tie a third line, you can modify the original code: function do_tie_line.

**Comment by rremigio** [comment]
If you want to tie the line widths of HeII, NIII, and Hbeta, you need to set the windex of all 3 lines to be the same number (e.g. 1). The following edit should accomplish this:

(4862.68,'Hb',4640.,5100.,'Hb_br',1,3e-3,0.0017,0.015,0.0022,0,**_1_**,0,0.05),
(4640.64,'Hb',4600.,4660.,'NIII4640',1,3e-3,0.0017,0.015,0.0022,0,**_1_**,1,0.001),
(4687.02,'Hb',4640.,5100.,'HeII4687',1,3e-3,0.0017,0.015,0.0022,0,**_1_**,1,0.003),

Similarly, the findex=1 setting you have (second from the right) for NIII and HeII means that you are tying the fluxes of these two lines. In this case, you are constraining the amplitude of the NIII line to be 0.001/0.003 = 1/3 of the HeII line. If you do not want these fluxes to be constrained, then findex should be set to 0 for both.

**Comment by LydiaMak** [comment]
Thanks! This works!
