### ISSUE TITLE
'_whole' broad lines calculation

### ISSUE THREAD

**Issue by LydiaMak** [legolason/PyQSOFit#29]
Hi,

Could you briefly explain to me the method that it's used in the code to calculate the the 'whole' FWHM etc for line that have multiple broad components?

Lydia

**Comment by legolason** [comment]
check peterson 2004 "CENTRAL MASSES AND BROAD-LINE REGION SIZES OF ACTIVE GALACTIC NUCLEI. II.
A HOMOGENEOUS ANALYSIS OF A LARGE REVERBERATION-MAPPING DATABASE"
