### ISSUE TITLE
Preferred Citation in ReadMe

### ISSUE THREAD

**Issue by augustfly** [legolason/PyQSOFit#3]
I see that you have created an ASCL identifier for this code; I also note that your code is being mentioned in manuscripts submitted to the AAS Journals.

I ask that you please list the preferred citation for your code in the main ReadMe file for this repository. If that citation is the ASCL identifier then it should read something like:

> The preferred citation for this code is Guo, Shen & Wang (2018), ascl:1809:008 
> @MISC{2018ascl.soft09008G,
    author = {{Guo}, H. and {Shen}, Y. and {Wang}, S.},
    title = "{PyQSOFit: Python code to fit the spectrum of quasars}",
    keywords = {Software },
    howpublished = {Astrophysics Source Code Library},
    year = 2018,
    month = sep,
    archivePrefix = "ascl",
    eprint = {1809.008},
    adsurl = {http://adsabs.harvard.edu/abs/2018ascl.soft09008G},
   adsnote = {Provided by the SAO/NASA Astrophysics Data System}
   }

Lastly, it would be good to document in this ReadMe the relationship between this code and other versions of the QSO fitting algorithms presented here. 

 August Muench
    Data Editor, AAS Journals.

**Comment by legolason** [comment]
Thanks for your suggestion!

**Comment by augustfly** [comment]
It appears to me that the preferred citation is in the ReadMe now, so I'm going to close this issue.
