### ISSUE TITLE
Question:q.flux and q.line_flux

### ISSUE THREAD

**Issue by LydiaMak** [legolason/PyQSOFit#35]
Hi,

Are q.flux and q.line_flux host or not host subtracted?

Thank you,

Lydia

**Comment by legolason** [comment]
depending on whether you do the host fitting or pca to separate the host

**Comment by LydiaMak** [comment]
This is the way I run it: 

q.Fit(name =None,nsmooth = 1, and_or_mask = False, deredden = True, reject_badpix = True, wave_range = None,\
      wave_mask =None, decomposition_host = True, Mi = None, npca_gal = 5, npca_qso = 20, \
      Fe_uv_op = True, Fe_flux_range=np.array([4435,4785]), poly = True, BC = True, rej_abs = False, \
      initial_guess = np.array([0., 3000., 0., 0.,1500., 0., 1., -1.5, 0., 15000., 0.5, 0., 0., 0.]), \
      MC = True, n_trails = 1, linefit = True, tie_lambda = True, tie_width = True, \
      tie_flux_1 = True, tie_flux_2 = True, save_result = True, plot_fig = True,save_fig = False, \
      plot_line_name = True, plot_legend = True, dustmap_path = path4, save_fig_path = path3, \
      save_fits_path = path2,save_fits_name = None)

I guess the second. Which means?

Lydia

**Comment by legolason** [comment]
Oh, here you subtract the host component, but for certain emission line regions e.g., hb or ha, we assume all the emission lines are from AGN. So when I subtract the host component, I will skip some line regions. see details in code line 548  block OIII, ha,NII,SII,OII,Ha,Hb,Hr,hdelta.
