### ISSUE TITLE
Fitting non-SDSS spectrum

### ISSUE THREAD

**Issue by LydiaMak** [legolason/PyQSOFit#36]
Hi,

If I fit an non-SDSS spectrum and I'd like to avoid interpolating this lower resolution spectrum to the higher SDSS one, is there something that I need to do for the iron templates? It seems that the iron fitting is problematic in this case but not sure...

Cheers,

Lydia

**Comment by legolason** [comment]
I do not think you need to change anything, the FeII template is deconvolved to pixel space then convolved to the spectral resolution you used and gives the FWHM.
