### ISSUE TITLE
Underfitting emission lines

### ISSUE THREAD

**Issue by astrohanp** [legolason/PyQSOFit#37]
Hi,

I have been using PyQSOFit for fitting spectra of emission line galaxies and I've noticed that the code seems to underfit multiple emission lines in a spectrum quite often. An example fit is attached below. For reference these spectra are from the DEIMOS 10k catalog. Any suggestions on how to tackle this issue or what might be causing it?
![Screen Shot 2022-06-28 at 3 38 00 PM](https://user-images.githubusercontent.com/12735796/176271705-598316e3-54b9-4eb5-985e-0872b8daba57.png)

**Comment by legolason** [comment]
OK, this is a simple issue caused by the default settings to fit qso. 
1) first use the narrow component to fit emission lines, 2)  if the real line width is still narrow than the lower limit of default settings, then change it (e.g., 1e-3  to 1e-4).

**Comment by astrohanp** [comment]
That worked thanks!
