### ISSUE TITLE
Fe complex persists even after disabling

### ISSUE THREAD

**Issue by astro-fermi** [legolason/PyQSOFit#43]
Hello,

Thanks for this great package. I am trying to fit an SDSS spectrum using the latest code. My input is as follows:

import glob, os,sys,timeit
import matplotlib
import numpy as np
from pyqsofit.PyQSOFit import QSOFit
from astropy.io import fits
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")
QSOFit.set_mpl_style()

data = fits.open(os.path.join(path_ex, 'data/spec-2788-54553-0051.fits'))
lam = 10**data[1].data['loglam']        # OBS wavelength [A]
flux = data[1].data['flux']             # OBS flux [erg/s/cm^2/A]
err = 1/np.sqrt(data[1].data['ivar'])   # 1 sigma error
z = data[2].data['z'][0]                # Redshift

ra = data[0].header['plug_ra']        # RA
dec = data[0].header['plug_dec']      # DEC
plateid = data[0].header['plateid']   # SDSS plate ID
mjd = data[0].header['mjd']           # SDSS MJD
fiberid = data[0].header['fiberid']   # SDSS fiber ID

q = QSOFit(lam, flux, err, z, ra=ra, dec=dec, plateid=plateid, mjd=mjd, fiberid=fiberid, path=path_ex)
q.Fit(name=None, nsmooth=1, and_or_mask=False, deredden=True, reject_badpix=False, wave_range=None,\
      wave_mask=None, decompose_host=False, Mi=None, npca_gal=5, npca_qso=20,\
      Fe_uv_op=False, Fe_flux_range=None, poly=True, BC=False, rej_abs=False, linefit=True,\
      initial_guess=None, \
      #MCMC=False, nburn=100, nsamp=200, nthin=10,  epsilon_jitter=1e-5, plot_corner=True,\
      save_result=True, plot_fig=True, save_fig=True, plot_line_name=True, plot_legend=True, \
      save_fig_path=path_out, save_fits_path=path_out, save_fits_name=None)

This plots the following output:

<img width="1016" alt="Screen Shot 2022-09-10 at 7 16 54 PM" src="https://user-images.githubusercontent.com/5036959/189486384-0560c07c-5f7e-4790-b374-925b79002c36.png">

As can be seen, even though I have disabled the Fe component, the code is still trying to fit it which leads to the poor fit of the [OII] line.

Interestingly, when I tried it with an older version of PyQsoFit, it did the job correctly:
<img width="973" alt="Screen Shot 2022-09-10 at 7 17 05 PM" src="https://user-images.githubusercontent.com/5036959/189486457-af332d31-031d-4393-a52a-326959e46ce4.png">

It would be great if you could please take a look and let me know a possible remedy.

**Comment by burke86** [comment]
Should be fixed in PR #45

**Comment by astro-fermi** [comment]
This issue is sorted out in the new version. Thanks for helping with this.
