### ISSUE TITLE
Inconsistent centerwave values stored in MCMC gauss results

### ISSUE THREAD

**Issue by astrohanp** [legolason/PyQSOFit#46]
Hi,

So I was going through your example.ipynb notebook and realized that the code is saving inconsistent centerwave values from the MCMC runs. Consider the following code excerpt from the example.ipynb

```
# Gaussian fitting results
print(q_mcmc.gauss_result_name)
print('')
print(q_mcmc.gauss_result)
```

> ['Hb_br_1_scale' 'Hb_br_1_scale_err' 'Hb_br_1_centerwave'
>  'Hb_br_1_centerwave_err' 'Hb_br_1_sigma' 'Hb_br_1_sigma_err'
>  'Hb_na_1_scale' 'Hb_na_1_scale_err' 'Hb_na_1_centerwave'
>  'Hb_na_1_centerwave_err' 'Hb_na_1_sigma' 'Hb_na_1_sigma_err'
>  'OIII4959c_1_scale' 'OIII4959c_1_scale_err' 'OIII4959c_1_centerwave'
>  'OIII4959c_1_centerwave_err' 'OIII4959c_1_sigma' 'OIII4959c_1_sigma_err'
>  'OIII5007c_1_scale' 'OIII5007c_1_scale_err' 'OIII5007c_1_centerwave'
>  'OIII5007c_1_centerwave_err' 'OIII5007c_1_sigma' 'OIII5007c_1_sigma_err'
>  'Ha_br_1_scale' 'Ha_br_1_scale_err' 'Ha_br_1_centerwave'
>  'Ha_br_1_centerwave_err' 'Ha_br_1_sigma' 'Ha_br_1_sigma_err'
>  'Ha_br_2_scale' 'Ha_br_2_scale_err' 'Ha_br_2_centerwave'
>  'Ha_br_2_centerwave_err' 'Ha_br_2_sigma' 'Ha_br_2_sigma_err'
>  'Ha_na_1_scale' 'Ha_na_1_scale_err' 'Ha_na_1_centerwave'
>  'Ha_na_1_centerwave_err' 'Ha_na_1_sigma' 'Ha_na_1_sigma_err'
>  'NII6549_1_scale' 'NII6549_1_scale_err' 'NII6549_1_centerwave'
>  'NII6549_1_centerwave_err' 'NII6549_1_sigma' 'NII6549_1_sigma_err'
>  'NII6585_1_scale' 'NII6585_1_scale_err' 'NII6585_1_centerwave'
>  'NII6585_1_centerwave_err' 'NII6585_1_sigma' 'NII6585_1_sigma_err'
>  'SII6718_1_scale' 'SII6718_1_scale_err' 'SII6718_1_centerwave'
>  'SII6718_1_centerwave_err' 'SII6718_1_sigma' 'SII6718_1_sigma_err'
>  'SII6732_1_scale' 'SII6732_1_scale_err' 'SII6732_1_centerwave'
>  'SII6732_1_centerwave_err' 'SII6732_1_sigma' 'SII6732_1_sigma_err']
> 
> [8.68700334e+00 1.01637686e-01 8.49006529e+00 7.91055207e-05
>  1.09929430e-02 1.31386254e-04 9.52499024e+00 1.37756743e-01
>  8.48916087e+00 2.22127131e-06 8.50657601e-04 4.75593423e-06
>  2.74390660e+01 4.17602049e-01 8.50903639e+00 0.00000000e+00
>  8.50657601e-04 0.00000000e+00 8.00441508e+01 3.85885690e-01
>  8.51865515e+00 0.00000000e+00 8.50657601e-04 0.00000000e+00
>  1.91934668e+01 4.09055820e-01 8.79087299e+00 5.83734285e-05
>  4.94704967e-03 4.57227276e-05 1.71879050e+01 6.54182588e-01
>  8.78853464e+00 9.25178445e-05 1.02397215e-02 7.73149317e-05
>  2.32468583e+01 1.73300314e-01 8.78925565e+00 5.30076034e-06
>  6.98470792e-04 8.59528736e-06 1.08016573e+01 6.24946073e-02
>  8.78700402e+00 0.00000000e+00 6.98470792e-04 0.00000000e+00
>  3.24049720e+01 0.00000000e+00 8.79239896e+00 0.00000000e+00
>  6.98470792e-04 0.00000000e+00 1.16004933e+01 8.31017257e-02
>  8.81239560e+00 0.00000000e+00 6.98470792e-04 0.00000000e+00
>  1.16004933e+01 0.00000000e+00 8.81453374e+00 0.00000000e+00
>  6.98470792e-04 0.00000000e+00]

```
# Gaussian fitting results
print(q_mcmc.gauss_result_name[::2])
print('')
print(q_mcmc.gauss_result_all)
print(np.shape(q_mcmc.gauss_result_all))
```

> ['Hb_br_1_scale' 'Hb_br_1_centerwave' 'Hb_br_1_sigma' 'Hb_na_1_scale'
>  'Hb_na_1_centerwave' 'Hb_na_1_sigma' 'OIII4959c_1_scale'
>  'OIII4959c_1_centerwave' 'OIII4959c_1_sigma' 'OIII5007c_1_scale'
>  'OIII5007c_1_centerwave' 'OIII5007c_1_sigma' 'Ha_br_1_scale'
>  'Ha_br_1_centerwave' 'Ha_br_1_sigma' 'Ha_br_2_scale' 'Ha_br_2_centerwave'
>  'Ha_br_2_sigma' 'Ha_na_1_scale' 'Ha_na_1_centerwave' 'Ha_na_1_sigma'
>  'NII6549_1_scale' 'NII6549_1_centerwave' 'NII6549_1_sigma'
>  'NII6585_1_scale' 'NII6585_1_centerwave' 'NII6585_1_sigma'
>  'SII6718_1_scale' 'SII6718_1_centerwave' 'SII6718_1_sigma'
>  'SII6732_1_scale' 'SII6732_1_centerwave' 'SII6732_1_sigma']
> 
> [[ 7.85981471e+00  9.70211243e-04  1.22709280e-02 ...  1.16004933e+01
>   -1.93092932e-04  6.98470792e-04]
>  [ 8.47034947e+00  6.09780117e-04  1.09293111e-02 ...  1.16004933e+01
>   -1.93092932e-04  6.98470792e-04]
>  [ 7.77712590e+00  1.57125188e-03  1.19115053e-02 ...  1.16004933e+01
>   -1.93092932e-04  6.98470792e-04]
>  ...
>  [ 8.08952745e+00  1.46338017e-03  1.19396797e-02 ...  1.16004933e+01
>   -1.93092932e-04  6.98470792e-04]
>  [ 8.18530017e+00  7.33854121e-04  1.16541468e-02 ...  1.16004933e+01
>   -1.93092932e-04  6.98470792e-04]
>  [ 8.52164429e+00  3.60590882e-04  1.09389864e-02 ...  1.16004933e+01
>   -1.93092932e-04  6.98470792e-04]]
> (1000, 33)

As you can see, for example, the Hb_br_1_centerwave value stored in q_mcmc.gauss_result (8.49006529e+00) vs the values stored in q_mcmc.gauss_result_all (9.70211243e-04) are different orders of magnitudes. It would be great if you could take a look at this issue since it is important in order to calculate error values for each parameter for narrow lines particularly. 

Thanks,
Rohan

**Comment by burke86** [comment]
Thanks, should be solved with PR #47

The fitting is done in d log wavelengths relative to the center wavelength of the complex for reasons involving simplifying the options to tie the lines together. Forgot to do the coordinate transform back to actual wavelength
