### ISSUE TITLE
Continuum fitting 

### ISSUE THREAD

**Issue by LydiaMak** [legolason/PyQSOFit#56]
I have a question with regards to the continuum fitting. I can see that iron continuum fitting depends on the windows given. I wanted to know if at any point the power law, the polynomial or the iron-optical avoid the ranges in the lines parameter.

Thank you.

Lydia

**Comment by legolason** [comment]
not full understand your question

**Comment by legolason** [comment]
not fully understand your question, you want to fit the line region without contamination from Iron template?

**Comment by LydiaMak** [comment]
No, I want the iron but I wonder if giving the ranges of the lines stops the polynomial and the power law fit at these wavelength even though there are continuum windows there.

**Comment by legolason** [comment]
No, continuum fit and emission line fit are separated.
