### ISSUE TITLE
Fitting an emission line with multiple gaussians

### ISSUE THREAD

**Issue by ktkauma** [legolason/PyQSOFit#6]
Hello,
Is it possible to fit a single emission line using multiple gaussian curves, and if so, how?   For example, if I have a quasar spectrum with a skewed broad HBeta line, is there some way to use two or three (or more) gaussian curves when fitting that specific line?  Any help is greatly appreciated!

**Comment by legolason** [comment]
Yes,  we can do that.  I am not sure you have seen my example,  fit single emission line or a skewed Hb is similar to this example  https://github.com/legolason/PyQSOFit/blob/master/example.ipynb

**Comment by ktkauma** [comment]
I had been looking at that, but maybe not carefully enough.  Is the place to specify number of gaussians used the 5th index of each entry in the 'newdata' array?  It looks like that is how Ha was fit in the example but I'm not sure.  Thanks!
