### ISSUE TITLE
Error using code on Google Colab

### ISSUE THREAD

**Issue by RodolfoFerro** [legolason/PyQSOFit#8]
Hello, 

I'm trying to replicate your example code (from example.ipynb), but I'm getting an error with some of the paths.

```
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-10-bd3ae4a2d819> in <module>()
      1 start = timeit.default_timer()
      2 # do the fitting
----> 3 q.Fit(name = None,nsmooth = 1, and_or_mask = False, deredden = True, reject_badpix = False, wave_range = None,      wave_mask =None, decomposition_host = True, Mi = None, npca_gal = 5, npca_qso = 20,       Fe_uv_op = True, poly = True, BC = False, rej_abs = False, initial_guess = None, MC = False,       n_trails = 5, linefit = True, tie_lambda = True, tie_width = True, tie_flux_1 = True, tie_flux_2 = True,      save_result = True, plot_fig ...
      4 
      5 end = timeit.default_timer()

9 frames
/usr/local/lib/python3.6/dist-packages/astropy/io/fits/util.py in fileobj_open(filename, mode)
    394     """
    395 
--> 396     return open(filename, mode, buffering=0)
    397 
    398 

FileNotFoundError: [Errno 2] No such file or directory: '.pca/Yip_pca_templates/gal_eigenspec_Yip2004.fits'
```

I'm sharing the notebook as I'm using it (with all the corresponding installations), so you can replicate the problem: https://colab.research.google.com/drive/1izwfcMRtefhgK_FuDf29fVwRshOPQyFg?usp=sharing

**Comment by RodolfoFerro** [comment]
Any help is appreciated.

**Comment by RodolfoFerro** [comment]
@legolason  @rudolffu Any help is appreciated.

**Comment by rudolffu** [comment]
Hi Rodolfo, I guess you need to keep the file structure as the same as that of PyQSOFit on github. So try loading the whole PyQSOFit directory into Colab, and run example.ipynb without changing relative paths. (p.s.: I'm also one of the users. @legolason is the main author of the code...)

**Comment by rudolffu** [comment]
I found one line in your code:
```
q = QSOFit(lam, flux, err, z, ra = ra, dec = dec, plateid = plateid, mjd = mjd, fiberid = fiberid, path = '.')
```
Consider change it to 
```
```
q = QSOFit(lam, flux, err, z, ra = ra, dec = dec, plateid = plateid, mjd = mjd, fiberid = fiberid, path = './')
```
to make the relative paths right.
```

**Comment by RodolfoFerro** [comment]
Hi @rudolffu , thanks for your quick response!

Even if I change the path as you mentioned, it still shows some errors (maybe from the dependencies ?):

```python
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-9-bd3ae4a2d819> in <module>()
      1 start = timeit.default_timer()
      2 # do the fitting
----> 3 q.Fit(name = None,nsmooth = 1, and_or_mask = False, deredden = True, reject_badpix = False, wave_range = None,      wave_mask =None, decomposition_host = True, Mi = None, npca_gal = 5, npca_qso = 20,       Fe_uv_op = True, poly = True, BC = False, rej_abs = False, initial_guess = None, MC = False,       n_trails = 5, linefit = True, tie_lambda = True, tie_width = True, tie_flux_1 = True, tie_flux_2 = True,      save_result = True, plot_fig ...
      4 
      5 end = timeit.default_timer()

8 frames
/usr/local/lib/python3.6/dist-packages/astropy/io/fits/util.py in fileobj_open(filename, mode)
    394     """
    395 
--> 396     return open(filename, mode, buffering=0)
    397 
    398 

FileNotFoundError: [Errno 2] No such file or directory: './qsopar.fits'
```

**Comment by rudolffu** [comment]
Hi, you need to generate the "qsopar.fits" file in advance as has been shown in ``https://github.com/legolason/PyQSOFit/blob/master/example.ipynb``. Reading the example might solve your problems.

**Comment by RodolfoFerro** [comment]
Thank you so much for all the help.

As you mentioned, I was able to perform the fit after generating the `qsopar.fits` file.
<center>
    <img src="https://user-images.githubusercontent.com/8453749/97084712-9617d780-15de-11eb-8106-9f8fc8b913f9.png" width="60%">
</center>

I'll proceed to close this issue.
