### ISSUE TITLE
Line flux calculation

### ISSUE THREAD

**Issue by B1GeasY** [legolason/PyQSOFit#9]
Hi,

I'm a newcomer in spectral line analysis and I got a question using your code. I noticed that you calculated the gaussian line flux by intergrating the area under the profile :
 
           if len(spline.roots()) > 0:
                fwhm_left, fwhm_right = spline.roots().min(), spline.roots().max()
                fwhm = abs(np.exp(fwhm_left)-np.exp(fwhm_right))/compcenter*c

                #calculate the total broad line flux
                area = (np.exp(xx)*yy*disp).sum()

For a gaussian profile, the area under it should equal the value of its scale (i,e. pp[0]), summing 'flux density*disp' can get the consistant area. Could you please tell me why you using 'wavelength*flux density*disp' instead of 'flux density*disp'?  Disp shoule have a unit of Angstrom so the unit of area is actually (erg/s/cm^2/A)*A*A ?

I'm confused here and Thank you in advance.

**Comment by legolason** [comment]
here, there is no unit for xx,  which is for frame transfer.   The area unit is still erg/cm^2/s. Hope it helps.

**Comment by B1GeasY** [comment]
Thanks I got it!
